version: 2

before:
  hooks:
    - go mod tidy

builds:
  - main: ./cmd/aoi
    binary: aoi
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w

archives:
  - formats: [tar.gz]
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}
    format_overrides:
      - goos: windows
        formats: [zip]

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^refactor:"
      - "^chore:"

release:
  prerelease: auto
  footer: >-
    ---

    **Full Changelog**: https://github.com/AlexandreSJ/aoi/compare/{{ .PreviousTag }}...{{ .Tag }}
