colors:
    primary: "32"
    secondary: "27"
    text: "231"
    dim: "8"
    title: "232"
    footer: "232"
    error: "162"
    success: "75"
system:
    config: ~/.config/aoi/config.yaml
    words: ~/.config/aoi/words
    quotes: ~/.config/aoi/quotes
